# change the default prefix from Ctrl-b to Ctrl-a
set -g prefix C-a

# unbind the old prefix (Ctrl-b) so it no longer works
unbind C-b

# bind Ctrl-a to send the prefix itself (so Ctrl-a Ctrl-a works inside tmux)
bind C-a send-prefix

# mimic Chrome tab shortcuts
bind -n C-t new-window
bind -n C-w kill-window

# status bar (clean minimal theme)
set -g status-style "bg=colour235,fg=colour250"
set -g window-status-current-format "#[bg=colour240,fg=colour255,bold] #I.#W "
set -g window-status-format "#[fg=colour247,bg=colour235] #I.#W "
set -g status-right "#[fg=colour235,bg=colour250] %Y-%m-%d #[fg=colour235,bg=colour245] %H:%M KST "
set -g status-left ""

# start window numbers from 1
set-option -g base-index 1
set-option -g pane-base-index 1

# disable prefix+c (create new window)
unbind c

# rename window via prefix+c
bind c command-prompt -I "#W" "rename-window '%%'"
